### PR TITLE
Fix: UML diagrams are not being generated

### PR DESCRIPTION
**Pull request by aleung**
PlantUML server has changed UML text encoding to raw deflate recently. It causes diagrams not being generated from this plugin but showing an decode error (#7).

Test case are updated and verified in PlantUML server version 1.2017.19 on http://www.plantuml.com/plantuml/uml/

### CODE REVIEW

**Comment by rpaterson** [comment]
This just bit me too.   Thank you for the fix @aleung!  Can we get this merged @markushedvall?  It's obviously right based on the image in the README

**Comment by thomas-lee** [comment]
I have encountered this problem too.
@markushedvall I look forward we can merge and have a awesome plantuml graph.

Thanks

**Comment by kyuwoo-choi** [comment]
yea I have same problem here. will you merged this please? @markushedvall

**Comment by markushedvall** [comment]
Thanks for this, I just had to spend some time to analyse the impact for backwards compatibility.

It seems plantuml (using the .jar) can decode both raw and none raw deflate, both in older and recent releases. I don't know why plantuml server no longer can decode none raw deflate though. I'm not totally sure but probably raw deflate should have been used in the first place.

In conclusion I will merge this and release without stepping the major version, as I consider this not breaking backwards compatibility.

**Pull request merged**
